FROM hypriot/rpi-alpine:latest

LABEL maintainer="yakumioto <yaku.mioto@gmail.com>"

ARG version=0.13.0

RUN set -ex \
    && apk add --no-cache tar curl \
    && curl -sSL https://github.com/fatedier/frp/releases/download/v${version}/frp_${version}_linux_arm.tar.gz | tar xz \
    && cd frp_${version}_linux_arm \
    && cp frpc frps /bin \
    && cd .. \
    && rm -rf frp_${version}_linux_arm