FROM hypriot/rpi-alpine:latest

LABEL maintainer="yakumioto <yaku.mioto@gmail.com>"

ARG version=0.13.0

RUN set -ex \
    && apk add --no-cache tar gzip curl \
    && curl -sSL https://github.com/fatedier/frp/releases/download/v${version}/frp_${version}_linux_arm.tar.gz | tar xz \
    && cp frp_${version}_linux_amd64/frpc frp_${version}_linux_amd64/frps /usr/bin \
    && rm -rf frp_${version}_linux_arm